<template>
  <v-card-text>
I'm nowhere near settling with my knowledge base. I keep a list of things I want to learn and implement in my future projects:

<ul style="list-style-type: none">
    <li><v-icon>mdi-react</v-icon> React. Done a basic to-do-app, but really want to take a deeper dive. With my Vue experience component logic is already clear, but there are definitely some differences to keep in mind in the developing flow</li>
    <li><v-icon>mdi-language-typescript</v-icon> Typescript. Generic "undefined" console errors are the worst, right? I've known about Typescript for a while and hope to make my code more streamlined with it in my future projects</li>
    <li><v-icon>mdi-brush</v-icon> sass/css. As I've used Front End libraries I haven't yet had the need to make extensive stylesheets for my projects. The things I needed to personalise I overwrote with vanilla CSS. But I'd like to get more comfortable with preprocessors for sure.</li>
    <li><v-icon>mdi-cog-clockwise</v-icon> Unit testing. Would love to take a deeper dive there to help create unit tests for my UIs.</li>
</ul>


  </v-card-text>
</template>
